backend:
  name: github
  repo: guirreri/gridsome-netlify-cms-issue
  branch: many-to-many-relationship-hack

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - label: "Blogs"
    name: "blogs"
    folder: "blogs"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "ID", label: "id", widget: "id" }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
  - label: "Posts"
    name: "posts"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - {
        label: "Blog",
        name: "blogs",
        widget: "relation",
        collection: "blogs",
        displayFields: ["title"],
        searchFields: ["title"],
        valueField: "title",
        multiple: true
      }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
      # Using a "list" widget works, but is not ideal! Would prefer relation
      # widget referring to a separate "blogs" collection.
      # In this case, Blogs can not have any custom properties and do not have
      # dedicated markdown files.
      # Also, if a blog is not typed out just right, a new one will be created.
      # - {label: "Blogs", name: "blogs", widget: "list"}